### PR TITLE
Added rudimentary frequency visualizer

### PR DESCRIPTION
**Pull request by mrange**

### CODE REVIEW

**Comment by essenbee** [comment]
Many thanks for this! I'll look at resolving the conflicts with the up-to-date code.

**Comment by mrange** [comment]
Fixed

**Comment by mrange** [comment]
Also added a waveform visualizer.

**Comment by essenbee** [comment]
Wow, thanks so much! I'll look at this later

**Comment by essenbee** [comment]
Addresses #7 and #8.

**Review by essenbee — APPROVED** [review]
Thank you so much for this PR, it looks amazing!

**Pull request merged**
